apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hello-nginx-read
  namespace: apps
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
